const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const qa = path.resolve('data/qa');
  fs.mkdirSync(qa, { recursive: true });
  const jobId = '6e5a8bb5276044399a3b106f67ac74ab';
  const legacyId = 'c95a16acbe094270b8aa96fe963eff2c';
  const cpuId = '6671062584ec4c12be2237b13a3c6e44';
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:8765/');
    await page.locator('.tabs').getByRole('button', { name: /断面2D/ }).click();
    await page.getByLabel('結果ジョブ').selectOption(jobId);
    await page.locator('.slice-canvas-host canvas[data-plane="xz"][data-step="4"]').waitFor();
    const graph = page.locator('.slice-canvas-host canvas');
    assert(Number(await graph.getAttribute('data-points')) > 0);
    const image = () => graph.evaluate(canvas => canvas.toDataURL());
    const initial = await image();
    await page.screenshot({ path: path.join(qa, 'section_xz_desktop.png'), fullPage: true });
    await page.getByRole('checkbox', { name: '電場の方向' }).check();
    await page.waitForFunction(previous => document.querySelector('.slice-canvas-host canvas').toDataURL() !== previous, initial);
    await page.getByLabel('断面の表示量').selectOption('e_norm_v_m');
    await page.getByLabel('電場の大きさ |E|の2D断面').waitFor();
    await page.getByLabel('色範囲の下限', { exact: true }).fill('100');
    await page.getByLabel('色範囲の上限', { exact: true }).fill('50');
    await page.getByRole('alert').filter({ hasText: '下限を上限より小さく' }).waitFor();
    await page.getByRole('button', { name: '自動範囲', exact: true }).click();
    await page.getByRole('checkbox', { name: '気相のみ' }).check();
    await page.getByRole('button', { name: '断面を拡大' }).click();
    assert.equal(await page.locator('.slice-zoom span').innerText(), '2×');
    await graph.scrollIntoViewIfNeeded();
    const beforePan = await image(), box = await graph.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 55, box.y + box.height / 2 + 25, { steps: 4 }); await page.mouse.up();
    await page.waitForFunction(previous => document.querySelector('.slice-canvas-host canvas').toDataURL() !== previous, beforePan);
    await page.getByRole('button', { name: '断面の表示範囲をリセット' }).click();
    await page.getByRole('checkbox', { name: '気相のみ' }).uncheck();
    await page.getByLabel('断面の表示量').selectOption('potential_v');
    const downloadPNG = page.waitForEvent('download');
    await page.getByRole('button', { name: 'PNG保存', exact: true }).click();
    const png = await downloadPNG; await png.saveAs(path.join(qa, 'section_export.png'));
    const bytes = fs.readFileSync(path.join(qa, 'section_export.png'));
    assert.equal(bytes.subarray(1, 4).toString(), 'PNG');
    assert(bytes.readUInt32BE(16) > 500 && bytes.readUInt32BE(20) > 350);
    const downloadCSV = page.waitForEvent('download');
    await page.getByRole('button', { name: '断面CSV', exact: true }).click();
    const csv = await downloadCSV; await csv.saveAs(path.join(qa, 'section_export.csv'));
    const rows = fs.readFileSync(path.join(qa, 'section_export.csv'), 'utf8').replace(/^\uFEFF/, '').split(/\r?\n/);
    assert(rows[0].includes('x_nm,y_nm,z_nm,material,potential_v,e_x_v_m'));
    assert(rows.length > 10000);
    assert.equal(rows[1].split(',')[0], 'xz');
    assert.equal(rows[1].split(',')[3], '4');
    await page.getByLabel('断面の向き').selectOption('xy');
    await page.locator('.slice-canvas-host canvas[data-plane="xy"]').waitFor();
    assert.equal(await page.getByLabel('断面位置 nm', { exact: true }).inputValue(), '1200');
    await page.getByLabel('断面の表示量').selectOption('sigma_c_m2');
    await page.getByLabel('表面電荷密度の2D断面').waitFor();
    await page.screenshot({ path: path.join(qa, 'section_charge_xy.png'), fullPage: true });
    const chargeDownload = page.waitForEvent('download');
    await page.getByRole('button', { name: '断面CSV', exact: true }).click();
    const chargeCSV = await chargeDownload; await chargeCSV.saveAs(path.join(qa, 'section_charge.csv'));
    const chargeRows = fs.readFileSync(path.join(qa, 'section_charge.csv'), 'utf8').replace(/^\uFEFF/, '').split(/\r?\n/);
    assert(chargeRows[0].endsWith('sigma_c_m2'));
    assert(chargeRows.length > 5 && chargeRows[1].includes(',segment,'));
    await page.getByLabel('断面位置 nm', { exact: true }).fill('999999');
    await page.getByRole('alert').filter({ hasText: '範囲で指定' }).waitFor();
    await page.getByRole('button', { name: '中央へ', exact: true }).click();
    await page.locator('.slice-canvas-host canvas').waitFor();
    await page.getByLabel('断面の向き').selectOption('yz');
    await page.locator('.slice-canvas-host canvas[data-plane="yz"]').waitFor();
    await page.getByLabel('断面の表示量').selectOption('e_norm_v_m');
    await graph.scrollIntoViewIfNeeded();
    const hoverBox = await graph.boundingBox();
    await page.mouse.move(hoverBox.x + hoverBox.width / 2, hoverBox.y + hoverBox.height / 2);
    await page.waitForFunction(() => document.querySelector('.slice-readout').textContent.includes('V/m'));
    assert((await page.locator('.slice-readout').innerText()).includes('格子点'));
    await page.getByLabel('断面の向き').selectOption('vertical');
    await page.getByLabel('断面角度 deg').fill('37');
    await page.locator('.slice-canvas-host canvas[data-plane="vertical"]').waitFor();
    await page.getByLabel('断面の表示量').selectOption('e_z_v_m');
    await page.locator('.time-select select').selectOption('1');
    await page.locator('.slice-canvas-host canvas[data-step="1"]').waitFor();
    assert((await page.locator('.slice-info').innerText()).includes('250'));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(qa, 'section_mobile.png'), fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile layout overflowed');
    await page.getByLabel('結果ジョブ').selectOption(legacyId);
    await page.locator(`.slice-canvas-host canvas[data-job-id="${legacyId}"]`).waitFor();
    let delayed = false;
    await page.route(`**/api/jobs/${jobId}/slice?**`, async route => {
      const response = await route.fetch(); delayed = true;
      await new Promise(resolve => setTimeout(resolve, 450));
      await route.fulfill({ response }).catch(() => {});
    });
    await page.getByLabel('結果ジョブ').selectOption(jobId);
    await page.waitForFunction(() => document.querySelector('.slice-canvas-host')?.getAttribute('aria-busy') === 'true');
    await page.waitForTimeout(300);
    await page.getByLabel('結果ジョブ').selectOption(cpuId);
    await page.locator(`.slice-canvas-host canvas[data-job-id="${cpuId}"]`).waitFor();
    await page.waitForTimeout(550);
    assert.equal(await graph.getAttribute('data-job-id'), cpuId);
    await page.getByLabel('結果ジョブ').selectOption('');
    await page.getByRole('heading', { name: '結果を待っています' }).waitFor();
    assert.equal(await graph.count(), 0);
    assert.deepEqual(errors, []);
    const report = { job_id: jobId, directions: ['xz', 'yz', 'xy', 'vertical'], hover_readout: true, charge_lines: true, saved_time: true, field_arrows: true,
      custom_range_validation: true, zoom_pan: true, png_export: true, csv_grid_rows: rows.length - 1,
      csv_surface_rows: chargeRows.length - 1, legacy_job: true, mobile_fits: true, job_switch: true, delayed_request: delayed, browser_errors: errors };
    fs.writeFileSync(path.join(qa, 'section_ui_check.json'), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
